# Data configuration
data:
  symbol: 'ZN=F'  # 10-year Treasury futures
  start_date: '2010-01-01'
  end_date: '2024-12-31'
  train_ratio: 0.8
  raw_data_path: 'data/raw/price_data.csv'
  processed_data_path: 'data/processed/'
  normalize: true

# Environment configuration
environment:
  initial_cash: 100000
  transaction_cost: 0.001
  position_limit: 1
  window_size: 20
  reward_scaling: 1.0

# Feature engineering
features:
  technical_indicators:
    - "sma"  # Simple Moving Average
    - "ema"  # Exponential Moving Average
    - "rsi"  # Relative Strength Index
    - "macd"  # Moving Average Convergence Divergence
    - "bollinger"  # Bollinger Bands
  lookback_periods: [5, 10, 20, 50]

# Training configuration
training:
  total_timesteps: 100000
  seed: 42
  ppo_params:
    learning_rate: 0.0003
    n_steps: 2048
    batch_size: 64
    n_epochs: 10
    gamma: 0.99
    gae_lambda: 0.95
    clip_range: 0.2
    ent_coef: 0.01
    vf_coef: 0.5
    max_grad_norm: 0.5

# Logging configuration
logging:
  log_dir: 'logs/training'
  tensorboard_dir: 'logs/tensorboard'
  eval_freq: 10000
  n_eval_episodes: 5
  save_freq: 50000 